// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsAHaWG1fQ3GhFyVatkBnRLX1R8OyC_c0',
    appId: '1:180504558248:web:1740065a75ad2ac899609d',
    messagingSenderId: '180504558248',
    projectId: 'dcplay-a688d',
    authDomain: 'dcplay-a688d.firebaseapp.com',
    storageBucket: 'dcplay-a688d.appspot.com',
    measurementId: 'G-9220716L8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHb0HtSvXD30DKqCbbNrNwJfxD4X9gCYY',
    appId: '1:180504558248:android:ef7103e4ef9c9c1199609d',
    messagingSenderId: '180504558248',
    projectId: 'dcplay-a688d',
    storageBucket: 'dcplay-a688d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiHXmlR5Zht2joPbqkjDowq0WCTY4snGg',
    appId: '1:180504558248:ios:566373ce0fe5ad1a99609d',
    messagingSenderId: '180504558248',
    projectId: 'dcplay-a688d',
    storageBucket: 'dcplay-a688d.appspot.com',
    androidClientId: '180504558248-ggr0o69jns63h8an67r7ftbhhu11r5u1.apps.googleusercontent.com',
    iosClientId: '180504558248-uke93lm93qmmsbcpetspt7almsu2mf0o.apps.googleusercontent.com',
    iosBundleId: 'com.dclive.dcplaytv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiHXmlR5Zht2joPbqkjDowq0WCTY4snGg',
    appId: '1:180504558248:ios:566373ce0fe5ad1a99609d',
    messagingSenderId: '180504558248',
    projectId: 'dcplay-a688d',
    storageBucket: 'dcplay-a688d.appspot.com',
    androidClientId: '180504558248-ggr0o69jns63h8an67r7ftbhhu11r5u1.apps.googleusercontent.com',
    iosClientId: '180504558248-uke93lm93qmmsbcpetspt7almsu2mf0o.apps.googleusercontent.com',
    iosBundleId: 'com.dclive.dcplaytv',
  );
}
